name: Release Drafter

on:
  push:
    branches:
    - main

jobs:
  release-drafter:
    name: Release Drafter
    runs-on: ubuntu-latest
    steps:
    - uses: release-drafter/release-drafter@v6
      with:
        disable-releaser: github.ref != 'refs/heads/main'
        config-name: release-drafter.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
